#!/bin/bash

# Получаем входные данные от пользователя
echo "Enter the first number between 1 and 10:"
read num1

echo "Enter the second number between 1 and 10:"
read num2

# Сравниваем числа и выводим результат
if [ $num1 -ge 1 -a $num1 -le 10 -a $num2 -ge 1 -a $num2 -le 10 ]; then
    if [ $num1 -gt $num2 ]; then
        echo "$num1 is greater than $num2."
        count=$num2
        # Выводит числовую последовательность
        while [ $num1 -ge $count ]; do 
            echo "$count"
            ((count++))
        done

    elif [ $num1 -lt $num2 ]; then
        echo "$num2 is greater than $num1."
        count=$num1

        # Выводит числовую последовательность
        while [ $count -le $num2 ]; do 
            echo "$count"
            ((count++))
        done

    else
        echo "The numbers are equal."
        echo "$num1"
    fi
else
    echo "Invalid input. Please enter a number between 1 and 10."
fi